# Generated by Django 3.2.2 on 2023-02-04 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'verbose_name': 'comic', 'verbose_name_plural': 'comics'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'wish list', 'verbose_name_plural': 'wish lists'},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='buied_qty',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='comic_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='bought_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='bought qty'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='comic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic', verbose_name='comic'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='marvel_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='marvel id'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='picture',
            field=models.URLField(default='', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.FloatField(default=0.0, max_length=5, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cart',
            field=models.BooleanField(default=False, verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='favorite'),
        ),
    ]
